# Site settings
title: Tianxiang
email: gaotx88@gmail.com
description: "CS61A"
baseurl: "/CS61A"
url: "http://gaotx.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
